---
title: "VOL VAR CALCULATION"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list =ls())
```


```{r, warning=FALSE, message=FALSE}
library(xts)
library(quantreg)
library(rugarch)
library(fBasics)
library(quantmod)
```

Load data

```{r}
load("~/Dropbox/Research Seminar/R/R data/dailyreturn.Rda")
# load("~/Dropbox/Research Seminar/R/R data/weeklyreturn.Rda")
```

```{r}
#dailyreturn <- weeklyreturn

stock.name <- names(dailyreturn)
stock.number <- length(stock.name)
stock.length <- dim(dailyreturn)[1]
```

# Calculate different Volatilities 

Initalize data.frames

```{r}
dailyvol_e_GARCH <- dailyreturn
dailyvol_e_GARCH[] <- NA

dailyvol_gjr_GARCH <- dailyreturn
dailyvol_gjr_GARCH[] <- NA
```

```{r}

i <- 1
  mydata <- dailyreturn[,i]
  
  myvol_e <- mydata 
  myvol_e[] <- NA
  
  myvol_gjr <- mydata 
  myvol_gjr[] <- NA
  
  NonNAindex <- which(!is.na(mydata))
  firstNonNA <- min(NonNAindex)
  length <- dim(mydata)[1]

  spec_gjr <- ugarchspec(mean.model=list( include.mean=T),
                   variance.model=list(model='gjrGARCH', garchOrder=c(1,1), distribution.model="std"))
    
  # Specifiy model
  model <- ugarchfit(spec=spec_gjr,data=mydata[firstNonNA:length])
  
  dof <- coef(model)[4] # Estimated Degrees of Freedom of Student-t residuals

  # Get conditional standard deviation.
  myvol_gjr[firstNonNA:length] <- sigma(model)
  
 qt(0.5,dof)  
  
# VaR from a GARCH model
a <- 0.95
wealth <- 200
var_garch_r <- qt(1-a,dof)*myvol_gjr + mean(mydata) # VaR in log-returns / use 'qnorm' for Gaussian residuals.
var_garch_w <- wealth*(1-exp(var_garch_r)) # VaR of 200 USD invested in stock.
  

series <- cbind(csd,myvol_gjr)

plot.zoo(series,main=stock.name[i])  
```

```{r}
data <- as.vector(g)
fit2 <- coef(fitdist(data,"t.scaled",
                  start=list(df=3,mean=mean(data),sd=sd(data))))
```

```{r}
class(fit2)
```


```{r,warning=FALSE}

i <- 1
g = dailyreturn[,i]
m <- mean(g,na.rm=TRUE)
std <- sqrt(var(g,na.rm=TRUE))

shape[i,]    

hist(dailyreturn[,i],density=20,probability = TRUE,breaks=100,main = stock.name[i],ylim=c(0,0.01))
curve(dt.scaled(x, df=shape[i,1],mean=shape[i,2],sd=shape[i,3]), add=TRUE, col='red' )
curve(dnorm(x, mean=m, sd=std), 
          col="darkblue", lwd=2, add=TRUE, yaxt="n")
# 
# dt.scaled(0.01, df=fit2[1],mean=fit2[2],sd=fit2[3])
# 
# qt(0.05,fit2[1])
# qnorm(0.05)

```





```{r, warning=FALSE}
start <- 1
end <- stock.number

for (i in start:end) {

  mydata <- dailyreturn[,i]
  
  myvol_e <- mydata 
  myvol_e[] <- NA
  
  myvol_gjr <- mydata 
  myvol_gjr[] <- NA
  
  NonNAindex <- which(!is.na(mydata))
  firstNonNA <- min(NonNAindex)
  length <- dim(mydata)[1]

# # e-GARCH
#   
#   spec_e <- ugarchspec(mean.model=list(armaOrder=c(1,1), include.mean=T),
#                    variance.model=list(model='eGARCH', garchOrder=c(1,1), distribution.model="std"))
# 
#   myvol_e[firstNonNA:length] <- sigma(ugarchfit(spec=spec_e,data=mydata[firstNonNA:length]))
#   dailyvol_e_GARCH[,i] <- myvol_e

# gjr-GARCH
  
  spec_gjr <- ugarchspec(mean.model=list(armaOrder=c(1,1), include.mean=T),
                   variance.model=list(model='gjrGARCH', garchOrder=c(1,1), distribution.model="std"))
    
  # Specifiy model
  model <- ugarchfit(spec=spec_gjr,data=mydata[firstNonNA:length])
  
  # Get conditional standard deviation.
  myvol_gjr[firstNonNA:length] <- sigma(model)
  
  # Forecast next day 
  csd <- ugarchforecast(model,n.ahead = 1)
  
  
  csd <- as.numeric(sigma(csd)) # Forecast tomorrows conditional standard deviation.

  dof <- coef(m)[4] # Estimated DoF of Student-t residuals


# VaR from a GARCH model
a <- 0.95
wealth <- 200
var_garch_r <- qt(1-a,dof)*csd + r.m # VaR in log-returns / use 'qnorm' for Gaussian residuals.
var_garch_w <- wealth*(1-exp(var_garch_r)) # VaR of 200 USD invested in stock.
  
  
  
  
  
  
  print(paste0("Progress: ",round(i/end*100,2), " %"))
  
  
  m <- ugarchfit(spec=spec,data=x)

  
}
```

Save

```{r}
#save(dailyvol_e_GARCH,file="../R data/dailyvol_e_GARCH.Rda")
save(dailyvol_gjr_GARCH,file="../R data/dailyvol_gjr_GARCH.Rda")
```

# Calculate different VaRs
# gjr_GARCH

```{r,warning=FALSE}
dailyvar_001 <- dailyreturn
dailyvar_001[] <- NA

dailyvar_01 <- dailyreturn
dailyvar_01[] <- NA

dailyvar_05 <- dailyreturn
dailyvar_05[] <- NA

dailyvar_10 <- dailyreturn
dailyvar_10[] <- NA
```

```{r,warning=FALSE}
for (i in 1:stock.number) {

  mydata <- dailyreturn[,i]
  
  myvol <- dailyvol_gjr_GARCH[,i]
  
  myvar <- mydata 
  myvar[] <- NA
  
  NonNAindex <- which(!is.na(mydata))
  firstNonNA <- min(NonNAindex)
  length <- dim(mydata)[1]

  myvar[firstNonNA:length] <- mean(mydata[firstNonNA:length]) + qnorm(0.001)*myvol[firstNonNA:length]
  dailyvar_001[,i] <- myvar
  
  myvar[firstNonNA:length] <- mean(mydata[firstNonNA:length]) + qnorm(0.01)*myvol[firstNonNA:length]
  dailyvar_01[,i] <- myvar

  myvar[firstNonNA:length] <- mean(mydata[firstNonNA:length]) + qnorm(0.05)*myvol[firstNonNA:length]
  dailyvar_05[,i] <- myvar

  myvar[firstNonNA:length] <- mean(mydata[firstNonNA:length]) + qnorm(0.10)*myvol[firstNonNA:length]
  dailyvar_10[,i] <- myvar

  print(paste0("Progress: ",round(i/stock.number*100,2), " %"))
}

```

```{r}

save(dailyvar_001,file="../R data/dailyvar_001.Rda")
save(dailyvar_01,file="../R data/dailyvar_01.Rda")
save(dailyvar_05,file="../R data/dailyvar_05.Rda")
save(dailyvar_10,file="../R data/dailyvar_10.Rda")
```


Save weekly

```{r}
# weeklyvar_01 <- dailyvar_01
# weeklyvar_05 <- dailyvar_05
# weeklyvar_10 <- dailyvar_10
```


```{r}
# save(weeklyvar_01,file="../R data/weeklyvar_01.Rda")
# save(weeklyvar_05,file="../R data/weeklyvar_05.Rda")
# save(weeklyvar_10,file="../R data/weeklyvar_10.Rda")
```

