---
title: "SSVAR vs SRISK"
---

```{r}
rm(list =ls())
```

```{r}
library(xtable)
library(ggplot2)
```


```{r}
load("~/Dropbox/Research Seminar/R/Result data/result_daily.Rda")
mydata <- result_daily[-28,]
```


```{r}
attach(mydata)

#Options
pos <- 3

setwd("~/Dropbox/Research Seminar/R/Graphs/Ergebnisse")
png("Scatter_Combo_01.png",width = 3000, height = 1000, res=110)

op <- par(mfcol=c(1,3),oma=c(1,0,0,0),cex=2,lwd=3)

par(pty="s",mar=c(4,3,2,0))

# Plot 1

x <- CoVaR_Mrd_USD
y <- SRISK_Mrd_USD

i <- -10


text.x <- CoVaR_Mrd_USD[CoVaR_Mrd_USD<(i) | SRISK_Mrd_USD<(i)]
text.y <- SRISK_Mrd_USD[CoVaR_Mrd_USD<(i) | SRISK_Mrd_USD<(i)]
text.lab <- Ticker[CoVaR_Mrd_USD<(i) | SRISK_Mrd_USD<(i)]

plot(x,y,
     ylab="SRISK in $ bn",xlab="",
     xlim = c(-45,0),ylim = c(-45,0),las=1)

text(text.x,text.y,labels=text.lab, cex=0.7 ,pos=pos, offset = 0.7)
abline(a=0,b=1,lty=2)
abline(lm(y ~ x),lty=1)

#abline(lm(text.y ~ text.x),lty=1)

# ===========================
# Plot 2

par(pty="s",mar=c(4,0,2,0))

x <- CoVaR_Mrd_USD
y <- SRISK_Mrd_USD

i <- -1
j <- -10


text.x <- CoVaR_Mrd_USD[CoVaR_Mrd_USD<(i) | SRISK_Mrd_USD<(i)]
text.y <- SRISK_Mrd_USD[CoVaR_Mrd_USD<(i) | SRISK_Mrd_USD<(i)]
text.lab <- Ticker[CoVaR_Mrd_USD<(i) | SRISK_Mrd_USD<(i)]

reg.x <- CoVaR_Mrd_USD[CoVaR_Mrd_USD>(j) & SRISK_Mrd_USD>(j)]
reg.y <- SRISK_Mrd_USD[CoVaR_Mrd_USD>(j) & SRISK_Mrd_USD>(j)]

plot(x,y,
     ylab="",xlab="SSVaR in $ bn",
     xlim = c(-10,0),ylim = c(-10,0),las=1)

text(text.x,text.y,labels=text.lab, cex=0.7 ,pos=pos, offset = 0.7)
abline(a=0,b=1,lty=2)
abline(lm(y ~ x),lty=1)

#abline(lm(reg.y ~ reg.x),lty=2)
# ===========================
# Plot 3

par(pty="s",mar=c(4,0,2,1))

x <- CoVaR_Mrd_USD
y <- SRISK_Mrd_USD

i <- -0
j <- -1


text.x <- CoVaR_Mrd_USD[CoVaR_Mrd_USD<(i) | SRISK_Mrd_USD<(i)]
text.y <- SRISK_Mrd_USD[CoVaR_Mrd_USD<(i) | SRISK_Mrd_USD<(i)]
text.lab <- Ticker[CoVaR_Mrd_USD<(i) | SRISK_Mrd_USD<(i)]

reg.x <- CoVaR_Mrd_USD[CoVaR_Mrd_USD>(j) & SRISK_Mrd_USD>(j)]
reg.y <- SRISK_Mrd_USD[CoVaR_Mrd_USD>(j) & SRISK_Mrd_USD>(j)]

plot(x,y,
     ylab="",xlab="",
     xlim = c(-1,0),ylim = c(-1,0),las=1)

text(text.x,text.y,labels=text.lab, cex=0.7 ,pos=pos, offset = 0.7)
abline(a=0,b=1,lty=2)
abline(lm(y ~ x),lty=1)

legend("bottomright",c("OLS","SRIKS = SVaR"),lty=c(1,2), bty="n",cex=0.75)

op
dev.off()
```


