---
title: "QUANTREG SCATTER PLOT"
---

```{r}
rm(list =ls())
```

```{r}
library(quantreg)
```

```{r}
load("~/Dropbox/Research Seminar/R/R data/dailyvar_01.Rda")
```

```{r}
stock.name <- colnames(dailyvar_01)
stock.number <- length(stock.name)
stock.length <- dim(dailyvar_01)[1]
index.number <- which(colnames(dailyvar_01)=="S&P 500")
```


```{r}
dailyvar <- as.matrix(dailyvar_01)
```


Set up plotting function
```{r}
myqrscatterplot <- function(i,lwd=1,cex=1,ylab=NULL,mar=c(6,8,3,2)) {
  FI <- NA
  Index <- NA
  FI <- dailyvar[,i]
  Index <- dailyvar[,index.number]
  
  x <- quantile(Index,0.01,na.rm=TRUE)
  
  Index1 <- Index[Index<x]
  FI1 <- FI[Index<x]
  
  Index0 <- Index[Index>x]
  FI0 <- FI[Index>x]
  
  cex.lab <- cex*1.25
  cex.point <- cex/1.5
  par(mar=mar,cex.lab=cex.lab,cex.main=cex.lab,lwd=lwd)
  plot(FI,Index,cex.axis=cex,type="n",xlab=paste0("VaR ",stock.name[i]),
       ylab="",las=1,lwd=lwd,
       xlim=c(-1,0),ylim=c(min(Index,na.rm = TRUE),0))
  title(ylab = ylab, mgp = c(5, 1, 0))
  title(main=stock.name[i],line = 1)

  
# 1 ohne points  
  points(FI,Index,cex=cex.point,col="grey25",pch=1)

# 2 OLS
  abline(lm(Index~FI),lty=1,col="black",cex=cex,lwd=lwd)  
  # legend("bottomright",c("OLS"),
  #        lty=c(1),lwd=lwd,
  #        col=c("black"), bty="n",cex=cex/1)

# 3 Mit Quantiles
    
  taus <- c(.75,.90,0.99)
  for( j in 1:length(taus)){
    abline(rq(Index~FI,tau=taus[j]),col="grey35",cex=cex,lwd=lwd,lty=2) 
  } 
  
  taus <- c(0.01,.1,.25)
  for( j in 1:length(taus)){
    abline(rq(Index~FI,tau=taus[j]),col="grey35",cex=cex,lwd=lwd,lty=3) 
  } 
  
  
#  abline(rq(Index~FI,tau=0.5),col="black",lty=2,cex=cex,lwd=lwd)

  legend("bottomright",c("Upper quantiles","OLS","Lower quantiles"),
         lty=c(2,1,3),lwd=lwd,
         col=c("grey35","black","grey35"), bty="n",cex=cex/1.15)

  
  

  
#  legend("bottomright",c("Upper quantiles","OLS","Lower quantiles","1% quantile S&P 500"),
#         lty=c(2,1,3,0),pch=c(26,26,26,6),lwd=lwd,
#         col=c("grey35","black","grey35"), bty="n",cex=cex/1.15)
  
  
#  points(FI1,Index1,cex=cex.point,col="grey25",pch=6)
#  points(FI0,Index0,cex=cex.point,col="grey25",pch=1)
  

  

}  
```


```{r}
setwd("~/Dropbox/Research Seminar/R/Graphs/Pr??si/Quantreg Scatter")
dailyvar <- as.matrix(dailyvar_01)
FI <- dailyvar[,1]
Index <- dailyvar[,1]

png("Scatter_Qreg_Combo_4.png",width = 1600, height = 1000, res=110)

myqrscatterplot(2,lwd=3,cex=1.5,ylab="VaR S&P 500")

dev.off()

```






